//Rergister User :
export const registerUser = async (req, res) => {
  try {
  } catch (error) {
    console.log("Internal Server Issue");
    res.status(500).json({ message: "Errror", error: error });
  }
};

//Login user :
export const loginUser = async (req, res) => {
  try {
  } catch (error) {
    console.log("Internal Server Issue");
    res.status(500).json({ message: "Errror", error: error });
  }
};

//Profile :
export const getProfile = async (req, res) => {
  try {
  } catch (error) {
    console.log("Internal Server Issue");
    res.status(500).json({ message: "Errror", error: error });
  }
};
